{{- $chartName := include "mapproxy-api.name" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- $tracing := (include "common.tracing.merged" .) | fromYaml }}
{{- $metrics := (include "common.metrics.merged" .) | fromYaml }}
{{- $redis := (include "common.redis.merged" .) | fromYaml }}

{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  TELEMETRY_TRACING_ENABLED: {{ $tracing.enabled | quote }}
  {{ if $tracing.enabled }}
  TELEMETRY_TRACING_URL: {{ $tracing.url }}
  {{ end }}
  TELEMETRY_METRICS_ENABLED: {{ $metrics.enabled | quote }}
  {{ if $metrics.enabled }}
  TELEMETRY_METRICS_URL: {{ $metrics.url }}
  {{ end }}
  MAPPROXY_CONFIG_PROVIDER: {{ quote $storage.mapproxyConfigProvider }}
  MAPPROXY_CACHE_GRIDS: {{ quote .Values.env.mapproxyCache.grids }}
  MAPPROXY_CACHE_UPSCALE_TILES: {{ quote .Values.env.mapproxyCache.upscaleTiles }}
  MAPPROXY_CACHE_DIRECTORY_LAYOUT: {{ quote .Values.env.mapproxyCache.directoryLayout }}
  REDIS_ENABLED: {{ quote $redis.enabled }}
  {{ if $redis.enabled }}
  REDIS_HOST: {{ quote $redis.host }}
  REDIS_PORT: {{ quote $redis.port }}
  REDIS_USER_ENABLED: {{ quote $redis.auth.enableRedisUser }}
  {{ if $redis.auth.enableRedisUser }}
  REDIS_USERNAME: {{ quote $redis.auth.username }}
  REDIS_PASSWORD: {{ quote $redis.auth.password }}
  {{ end }}
  REDIS_PREFIX_ENABLED: {{ quote $redis.prefix.enablePrefix }}
  {{ if $redis.prefix.enablePrefix }}
  REDIS_PREFIX: {{ quote $redis.prefix.prefix }}
  {{ end }}
  REDIS_TYPE: {{ quote $redis.type }}
  REDIS_DEFAULT_TTL: {{ quote $redis.default_ttl }}
  {{ end }}
  {{- if eq (upper $storage.mapproxyConfigProvider) "S3" }}
  {{- $s3 := (include "common.s3.merged" .) | fromYaml }}
  S3_ENDPOINT_URL: {{ $s3.endpointUrl }}
  S3_BUCKET:  {{ $s3.tilesBucket }}
  S3_SSL_ENABLED: {{ $s3.sslEnabled }}
  {{- end }}
  {{- if eq (upper $storage.mapproxyConfigProvider) "DB" }}
  {{- $db := (include "common.db.merged" .) | fromYaml }}
  DB_HOST: {{ $db.host }}
  DB_NAME: {{ $db.name }}
  DB_PORT: {{ $db.port | quote }}
  DB_SSL_ENABLE: {{ $db.sslEnabled | quote }}
  DB_SCHEMA: {{ $db.schema }}
  DB_SSL_REJECT_UNAUTHORIZED: {{ $db.dbRejectUnauthorized | quote  }}
  PGAPPNAME: {{ $chartName }}
  {{- end }}
{{- end }}
