{{- $chartName := include "mapproxy-api.name" . -}}
{{- $tracingUrl := include "mapproxy-api.tracingUrl" . -}}
{{- $metricsUrl := include "mapproxy-api.metricsUrl" . -}}
{{- $storage := (include "common.storage.merged" .) | fromYaml }}

{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  MAPPROXY_CONFIG_PROVIDER: {{ $storage.mapproxyConfigProvider }}
  MAPPROXY_CACHE_GRIDS: {{ quote .Values.env.mapproxyCache.grids }}
  MAPPROXY_CACHE_UPSCALE_TILES: {{ quote .Values.env.mapproxyCache.upscaleTiles }}
  MAPPROXY_CACHE_DIRECTORY_LAYOUT: {{ quote .Values.env.mapproxyCache.directoryLayout }}
  {{- if eq (upper $storage.mapproxyConfigProvider) "S3" }}
  {{- $s3 := (include "common.s3.merged" .) | fromYaml }}
  S3_ENDPOINT_URL: {{ $s3.endpointUrl }}
  S3_BUCKET:  {{ $s3.tilesBucket }}
  S3_SSL_ENABLED: {{ $s3.sslEnabled  }}
  {{- end }}
  {{- if eq (upper $storage.mapproxyConfigProvider) "DB" }}
  {{- $db := (include "common.db.merged" .) | fromYaml }}
  DB_HOST: {{ $db.host }}
  DB_NAME: {{ $db.name }}
  DB_PORT: {{ $db.port }}
  DB_SSL_ENABLE: {{ $db.sslEnabled }}
  DB_SCHEMA: {{ $db.schema }}
  DB_SSL_REJECT_UNAUTHORIZED: {{ $db.dbRejectUnauthorized }}
  PGAPPNAME: {{ $chartName }}
  {{- end }}
{{- end }}
