global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30999 #for minikube deployment only
resetOnConfigChange: true

cloudProvider:
  dockerRegistryUrl: 10.45.130.11:5000
  imagePullSecretName: 'my-registry-secret'
  flavor: minikube

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: mapproxy-api
  tag: 'tempalte1'

rasterCommon:
  storage:
    mapproxyConfigStorageProvider: 'DB'
    fs:
      tilesPvc:
        name: "internal-pvc"
        tilesSubPath: tiles
    s3:
      endpointUrl: "10.45.130.11:9000"
      tilesBucket: "dtm"
      sslEnabled: false
      secretName: "s3-secret"

  db:
    host: "10.45.130.11"
    name: "mapproxy-config-dev"
    port: 5432
    sslEnabled: true
    secrets:
      useExternal: false
      externalSecretName: ''

mapproxy:
    db:
      nameOverride:
      schema: MapproxyConfig

local: # for local stand alone deployment, external pvc and secrets should be used for full deployment  
  fs:
    createComponents: false
    storageClass: hostPath
    capacity: 5Gi
    accessMode: ReadWriteOnce
    hostPath: /hostDir
  db:
    createSecret: true
    userName: avi
    password: 
    rejectUnauthorized: false
    certs:
      ca: certs/rootCA.crt
      key: certs/avi.key
      cert: certs/avi.crt
  s3:
    createSecret: false
    secretAccessKey: minioadmin
    accessKeyId: minioadmin
  

env:
  port: 80
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  mapproxyCache:
    grids: epsg4326grid
    requestFormat: image/png
    upscaleTiles: 18
    directoryLayout: tms

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: false
  path: /
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
