name: Build and push artifacts

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_push_docker:
      uses: MapColonies/shared-workflows/.github/workflows/build-and-push-docker.yaml@v2
      secrets: inherit
      with:
        scope: raster

  build_and_push_helm:
      uses: MapColonies/shared-workflows/.github/workflows/build-and-push-helm.yaml@v2
      secrets: inherit
      with:
        scope: raster
