name: Lint

on: [pull_request]

jobs:
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          prettier: true
          eslint_extensions: ts
      - name: lint openapi spec file
        run: npm run lint:openapi
  # this is a place holder for an openapi lint, action is not mature enough to accept custom config.
  # openapi:
  #   name: Lint openapi3.yaml
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: OpenAPI Lint Checks
  #       uses: nwestfall/openapi-action@v1.0.1
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         file: openapi3.yaml
