name: pull_request

on: [pull_request]

jobs:
  pull_request:
    uses: MapColonies/shared-workflows/.github/workflows/pull_request.yaml@v2
    secrets: inherit
    with:
      enableOpenApiCheck: false
