name: "Publish release on tag push"

on:
  push:
    tags:
      - "v*"

jobs:
  release_on_tag_push:
    uses: MapColonies/shared-workflows/.github/workflows/release-on-tag-push.yaml@v2
    secrets: inherit
