name: "Publish release on tag push"

on:
  push:
    tags:
      - "v*"

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for CHANGELOG.md
        uses: actions/checkout@v2

      - name: Publish Release to Github
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
